### ISSUE TITLE
低版本node运行报错

### ISSUE THREAD

**Issue by yongjun925** [fym201/alipay-node-sdk#19]
meteor node -v
v4.8.4

node_modules/alipay-node-sdk/lib/utl.js:138
 
let ret = {response:res, body:body};
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

只要把这个let 改下就可以了

**Comment by fym201** [comment]
已修改

**Comment by yongjun925** [comment]
感谢，顺便可以更新下npm仓库么

**Comment by fym201** [comment]
@yongjun925 ok,已经更新了
