### ISSUE TITLE
ali.appPay返回的参数乱码

### ISSUE THREAD

**Issue by longxianlin** [fym201/alipay-node-sdk#22]
出现很多%%%%

**Comment by fym201** [comment]
正常的，返回的参数是进行了url编码的

**Comment by longxianlin** [comment]
这个接口不是返回统一收单交易创建接口？
`{
    "alipay_trade_create_response": {
        "code": "10000",
        "msg": "Success",
        "out_trade_no": "20150423001001",
        "trade_no": "2015042321001004720200028594"
    },
    "sign": "ERITJKEIJKJHKKKKKKKHJEREEEEEEEEEEE"
}`

**Comment by fym201** [comment]
生成的是组装好的请求体，客户端拿到直接发给支付宝，不需要修改

**Comment by longxianlin** [comment]
了解。
没找到，发送给支付宝的封装接口。

**Comment by longxianlin** [comment]
其它退款，查询你做了封装

**Comment by longxianlin** [comment]
怎么转成json？
