### ISSUE TITLE
let 关键字报错

### ISSUE THREAD

**Issue by bughp** [fym201/alipay-node-sdk#6]
你好，我的Nodejs 版本是 v4.4.5，能否给个可以运行的Demo呢？ 非常感谢（我不会Nodejs）！

**Comment by fym201** [comment]
test目录里有测试代码,你可以参考

**Comment by gavin1990** [comment]
utl.request = function(opts){
    return new Promise(function(resolve, reject){
        request(opts, function(err, res, body){
            if(err){
                reject(err);
                return;
            }
            let ret = {response:res, body:body};
            ret.ok = function() {
                return res.statusCode === 200;
            };
            ret.json = function () {
                if(res.body) return JSON.parse(res.body);
                return null;
            };
            resolve(ret);
        });
    });
};

这段代码中的  let ret = {response:res, body:body};这个一直报错  不能使用let

**Comment by fym201** [comment]
let是es6新增关键字，你可以升级node到最新版本，或者把let替换为var

**Comment by gavin1990** [comment]
@fym201  升级了  用的node版本是  6.10.3 ，还是不行，然后就把let改成var就可以了

**Comment by fym201** [comment]
你好，低版本node需要使用 --harmony 参数启用新特性
