### ISSUE TITLE
报错fs.readFileSync is not a function

### ISSUE THREAD

**Issue by luchenwei9266** [fym201/alipay-node-sdk#8]
您好，我参考了test下index.js代码，但是调起支付时，后台报了一个'fs.readFileSync is not a function'的错误。找了一下没发现解决办法，所以过来请教您一下。。。

**Comment by fym201** [comment]
你用的node是哪个版本？ 可以把错误信息发上来我看看。

**Comment by luchenwei9266** [comment]
![image](https://user-images.githubusercontent.com/9455826/27418420-95637e14-574d-11e7-92aa-870b7392359f.png)

node版本是6.10.0

**Comment by fym201** [comment]
你这是在前端用的，这个库是针对后端服务器的，前端不能直接用。你在后端按照例子生成支付参数，返回给前端使用

**Comment by luchenwei9266** [comment]
哦。好的。谢谢了。
